// app/layout.tsx
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import Footer from "@/components/home/Footer";
import { manrope, outfit, poppins } from "@/public/assets/css/font";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "font.creativestudio.in",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} ${outfit.className} ${manrope.className} antialiased`}>
        <div className="min-h-screen flex flex-col">
          <Navbar />

          <div className="app-layout flex flex-1">
            <LeftSidebar className="hidden lg:flex" />
            
            <main className="content flex-1 bg-black">
              {children}
              <Footer />
            </main>
            
            <RightSidebar className="hidden lg:flex" />
          </div>
        </div>
      </body>
    </html>
  );
}